languageCode = 'en-us'
paginate = 100
timeout = "60s"
disableKinds = ["RSS"]

# These can be changed here or overwritten with environment variables
# See https://gohugo.io/getting-started/configuration/#configure-with-environment-variables
title = "GitHub mirror" # FIXME
[Params]
  # owner and repository are used to link to the correct GitHub repo on external links
  # and to create local links to other mirrored issues and PRs
  owner = "placeholder-owner" # FIXME
  repository = "placeholder-repository" # FIXME
  footer = "This mirror is hosted by PLACEHOLDER."

[taxonomies]
  category = "contributor"
  tag = "labels"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineAnchors = ''
    lineNoStart = 0
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'github-dark'
    tabWidth = 2
