languageCode = 'en-us'
title = 'Bitcoin Core GitHub mirror'
paginate = 100

[taxonomies]
  category = "contributor"
  tag = "labels"
  series = 'milestone'


[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineAnchors = ''
    lineNoStart = 0
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'github-dark'
    tabWidth = 2
